#pragma once

enum STATUS
{
    STATUS_SUCCESS, // Success Status
    STATUS_OPEN_FAILED,
    STATUS_FILE_NOT_FOUND,
    STATUS_INVALID_DATA,
    STATUS_BAD_ARGUMENTS,
    STATUS_FILE_EXISTS,
    STATUS_BAD_EXTENSION
};

void STATUS_LOADER();