#pragma once

enum ERRORS
{
    ERROR_SUCCESS,
    ERROR_OPEN_FAILED,
    ERROR_FILE_NOT_FOUND,
    ERROR_INVALID_DATA,
    ERROR_BAD_ARGUMENTS,
    ERROR_FILE_EXISTS,
    ERROR_BAD_EXTENSION
};

void ERROR_LOADER();